ERROR    root:ConfigStarted.py:59 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x560fe8c147fa <unknown>
#1 0x560fe86b8e90 <unknown>
#2 0x560fe870a870 <unknown>
#3 0x560fe870aa91 <unknown>
#4 0x560fe86fe446 <unknown>
#5 0x560fe873026d <unknown>
#6 0x560fe86fe2fa <unknown>
#7 0x560fe873040e <unknown>
#8 0x560fe8756135 <unknown>
#9 0x560fe8730013 <unknown>
#10 0x560fe86fcb3b <unknown>
#11 0x560fe86fd7a1 <unknown>
#12 0x560fe8bd9b9b <unknown>
#13 0x560fe8bdda8a <unknown>
#14 0x560fe8bc1912 <unknown>
#15 0x560fe8bde604 <unknown>
#16 0x560fe8ba674f <unknown>
#17 0x560fe8c02678 <unknown>
#18 0x560fe8c02856 <unknown>
#19 0x560fe8c13666 <unknown>
#20 0x7f085da9caa4 <unknown>
#21 0x7f085db29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZGVfTFUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmx1L2RlL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9MVS9kZS9DTEUtS0xBU1NFL0NPVVBFP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNTUifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjQyMzYyMjg1Ny4xNzQ3MTIzNTA0In0sImFub25JZCI6IjU4ZDVjNGRmMDQ1MmUwOWYifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3MTUyNTYyNDEwODk0NDc1In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x560fe8c147fa <unknown>
#1 0x560fe86b8e90 <unknown>
#2 0x560fe86a0156 <unknown>
#3 0x560fe869ea6a <unknown>
#4 0x560fe869f1cf <unknown>
#5 0x560fe869f124 <unknown>
#6 0x560fe86bd11f <unknown>
#7 0x560fe87623ca <unknown>
#8 0x560fe8730242 <unknown>
#9 0x560fe8756135 <unknown>
#10 0x560fe8730013 <unknown>
#11 0x560fe86fcb3b <unknown>
#12 0x560fe86fd7a1 <unknown>
#13 0x560fe8bd9b9b <unknown>
#14 0x560fe8bdda8a <unknown>
#15 0x560fe8bc1912 <unknown>
#16 0x560fe8bde604 <unknown>
#17 0x560fe8ba674f <unknown>
#18 0x560fe8c02678 <unknown>
#19 0x560fe8c02856 <unknown>
#20 0x560fe8c13666 <unknown>
#21 0x7f085da9caa4 <unknown>
#22 0x7f085db29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNDIzNjIyODU3LjE3NDcxMjM1MDQifSwiYW5vbklkIjoiNThkNWM0ZGYwNDUyZTA5ZiJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5sdS9kZS9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvTFUvZGUvQ0xFLUtMQVNTRS9DT1VQRT9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU1IiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6NH0sIl90b29sc0V2ZW50TGlua0lkIjoiNDcyMDczNjQ5NDk4OTg3NTYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x560fe8c147fa <unknown>
#1 0x560fe86b8e90 <unknown>
#2 0x560fe86a0156 <unknown>
#3 0x560fe869ea6a <unknown>
#4 0x560fe869f1cf <unknown>
#5 0x560fe869f124 <unknown>
#6 0x560fe86bd11f <unknown>
#7 0x560fe87623ca <unknown>
#8 0x560fe8730242 <unknown>
#9 0x560fe8756135 <unknown>
#10 0x560fe8730013 <unknown>
#11 0x560fe86fcb3b <unknown>
#12 0x560fe86fd7a1 <unknown>
#13 0x560fe8bd9b9b <unknown>
#14 0x560fe8bdda8a <unknown>
#15 0x560fe8bc1912 <unknown>
#16 0x560fe8bde604 <unknown>
#17 0x560fe8ba674f <unknown>
#18 0x560fe8c02678 <unknown>
#19 0x560fe8c02856 <unknown>
#20 0x560fe8c13666 <unknown>
#21 0x7f085da9caa4 <unknown>
#22 0x7f085db29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Started_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: