ERROR    root:ConfigStarted.py:59 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55e1114627fa <unknown>
#1 0x55e110f06e90 <unknown>
#2 0x55e110f58870 <unknown>
#3 0x55e110f58a91 <unknown>
#4 0x55e110f4c446 <unknown>
#5 0x55e110f7e26d <unknown>
#6 0x55e110f4c2fa <unknown>
#7 0x55e110f7e40e <unknown>
#8 0x55e110fa4135 <unknown>
#9 0x55e110f7e013 <unknown>
#10 0x55e110f4ab3b <unknown>
#11 0x55e110f4b7a1 <unknown>
#12 0x55e111427b9b <unknown>
#13 0x55e11142ba8a <unknown>
#14 0x55e11140f912 <unknown>
#15 0x55e11142c604 <unknown>
#16 0x55e1113f474f <unknown>
#17 0x55e111450678 <unknown>
#18 0x55e111450856 <unknown>
#19 0x55e111461666 <unknown>
#20 0x7ff5c409caa4 <unknown>
#21 0x7ff5c4129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_united_kingdom_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZW5fR0IiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmNvLnVrL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9HQi9lbi9FLUtMQVNTRS9ULU1PREVMTD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU4In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI3MTMxNzc1NDAuMTc0NzEyMTk4MCJ9LCJhbm9uSWQiOiI0NDU3MWQ2M2YyOTQ0ODcyIn0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMzMyNTg3MTA5NjkwMDU3OCJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55e1114627fa <unknown>
#1 0x55e110f06e90 <unknown>
#2 0x55e110eee156 <unknown>
#3 0x55e110eeca6a <unknown>
#4 0x55e110eed1cf <unknown>
#5 0x55e110eed124 <unknown>
#6 0x55e110f0b11f <unknown>
#7 0x55e110fb03ca <unknown>
#8 0x55e110f7e242 <unknown>
#9 0x55e110fa4135 <unknown>
#10 0x55e110f7e013 <unknown>
#11 0x55e110f4ab3b <unknown>
#12 0x55e110f4b7a1 <unknown>
#13 0x55e111427b9b <unknown>
#14 0x55e11142ba8a <unknown>
#15 0x55e11140f912 <unknown>
#16 0x55e11142c604 <unknown>
#17 0x55e1113f474f <unknown>
#18 0x55e111450678 <unknown>
#19 0x55e111450856 <unknown>
#20 0x55e111461666 <unknown>
#21 0x7ff5c409caa4 <unknown>
#22 0x7ff5c4129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_united_kingdom_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNzEzMTc3NTQwLjE3NDcxMjE5ODAifSwiYW5vbklkIjoiNDQ1NzFkNjNmMjk0NDg3MiJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5jby51ay9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvR0IvZW4vRS1LTEFTU0UvVC1NT0RFTEw%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1OCIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjM3MDY4NjA1NDk1MTk2NzgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55e1114627fa <unknown>
#1 0x55e110f06e90 <unknown>
#2 0x55e110eee156 <unknown>
#3 0x55e110eeca6a <unknown>
#4 0x55e110eed1cf <unknown>
#5 0x55e110eed124 <unknown>
#6 0x55e110f0b11f <unknown>
#7 0x55e110fb03ca <unknown>
#8 0x55e110f7e242 <unknown>
#9 0x55e110fa4135 <unknown>
#10 0x55e110f7e013 <unknown>
#11 0x55e110f4ab3b <unknown>
#12 0x55e110f4b7a1 <unknown>
#13 0x55e111427b9b <unknown>
#14 0x55e11142ba8a <unknown>
#15 0x55e11140f912 <unknown>
#16 0x55e11142c604 <unknown>
#17 0x55e1113f474f <unknown>
#18 0x55e111450678 <unknown>
#19 0x55e111450856 <unknown>
#20 0x55e111461666 <unknown>
#21 0x7ff5c409caa4 <unknown>
#22 0x7ff5c4129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Started_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: