ERROR    root:ConfigStarted.py:59 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55ba284647fa <unknown>
#1 0x55ba27f08e90 <unknown>
#2 0x55ba27f5a870 <unknown>
#3 0x55ba27f5aa91 <unknown>
#4 0x55ba27f4e446 <unknown>
#5 0x55ba27f8026d <unknown>
#6 0x55ba27f4e2fa <unknown>
#7 0x55ba27f8040e <unknown>
#8 0x55ba27fa6135 <unknown>
#9 0x55ba27f80013 <unknown>
#10 0x55ba27f4cb3b <unknown>
#11 0x55ba27f4d7a1 <unknown>
#12 0x55ba28429b9b <unknown>
#13 0x55ba2842da8a <unknown>
#14 0x55ba28411912 <unknown>
#15 0x55ba2842e604 <unknown>
#16 0x55ba283f674f <unknown>
#17 0x55ba28452678 <unknown>
#18 0x55ba28452856 <unknown>
#19 0x55ba28463666 <unknown>
#20 0x7f8577c9caa4 <unknown>
#21 0x7f8577d29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_spain_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjEyMTQ0MTQxLjE3NDcxMjE5NTIifSwiYW5vbklkIjoiMTJjMGYzZWNjNTk2OTZiOCJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5lcy9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvRVMvZXMvQi1LTEFTU0UvU1BPUlRTJTIwVE9VUkVSP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNTYiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI4MzcxMDE5NzEwMTM5NDYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55ba284647fa <unknown>
#1 0x55ba27f08e90 <unknown>
#2 0x55ba27ef0156 <unknown>
#3 0x55ba27eeea6a <unknown>
#4 0x55ba27eef1cf <unknown>
#5 0x55ba27eef124 <unknown>
#6 0x55ba27f0d11f <unknown>
#7 0x55ba27fb23ca <unknown>
#8 0x55ba27f80242 <unknown>
#9 0x55ba27fa6135 <unknown>
#10 0x55ba27f80013 <unknown>
#11 0x55ba27f4cb3b <unknown>
#12 0x55ba27f4d7a1 <unknown>
#13 0x55ba28429b9b <unknown>
#14 0x55ba2842da8a <unknown>
#15 0x55ba28411912 <unknown>
#16 0x55ba2842e604 <unknown>
#17 0x55ba283f674f <unknown>
#18 0x55ba28452678 <unknown>
#19 0x55ba28452856 <unknown>
#20 0x55ba28463666 <unknown>
#21 0x7f8577c9caa4 <unknown>
#22 0x7f8577d29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_spain_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZXNfRVMiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmVzL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9FUy9lcy9CLUtMQVNTRS9TUE9SVFMlMjBUT1VSRVI%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1NiJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjEyMTQ0MTQxLjE3NDcxMjE5NTIifSwiYW5vbklkIjoiMTJjMGYzZWNjNTk2OTZiOCJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjJ9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxMzY4MTY1MTI0NDIwMjMyIn0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55ba284647fa <unknown>
#1 0x55ba27f08e90 <unknown>
#2 0x55ba27ef0156 <unknown>
#3 0x55ba27eeea6a <unknown>
#4 0x55ba27eef1cf <unknown>
#5 0x55ba27eef124 <unknown>
#6 0x55ba27f0d11f <unknown>
#7 0x55ba27fb23ca <unknown>
#8 0x55ba27f80242 <unknown>
#9 0x55ba27fa6135 <unknown>
#10 0x55ba27f80013 <unknown>
#11 0x55ba27f4cb3b <unknown>
#12 0x55ba27f4d7a1 <unknown>
#13 0x55ba28429b9b <unknown>
#14 0x55ba2842da8a <unknown>
#15 0x55ba28411912 <unknown>
#16 0x55ba2842e604 <unknown>
#17 0x55ba283f674f <unknown>
#18 0x55ba28452678 <unknown>
#19 0x55ba28452856 <unknown>
#20 0x55ba28463666 <unknown>
#21 0x7f8577c9caa4 <unknown>
#22 0x7f8577d29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Started_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: