ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x561de87287fa <unknown>
#1 0x561de81cce90 <unknown>
#2 0x561de821e870 <unknown>
#3 0x561de821ea91 <unknown>
#4 0x561de8212446 <unknown>
#5 0x561de824426d <unknown>
#6 0x561de82122fa <unknown>
#7 0x561de824440e <unknown>
#8 0x561de826a135 <unknown>
#9 0x561de8244013 <unknown>
#10 0x561de8210b3b <unknown>
#11 0x561de82117a1 <unknown>
#12 0x561de86edb9b <unknown>
#13 0x561de86f1a8a <unknown>
#14 0x561de86d5912 <unknown>
#15 0x561de86f2604 <unknown>
#16 0x561de86ba74f <unknown>
#17 0x561de8716678 <unknown>
#18 0x561de8716856 <unknown>
#19 0x561de8727666 <unknown>
#20 0x7fa9ec29caa4 <unknown>
#21 0x7fa9ec329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_spain_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZXNfRVMiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmVzL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9FUy9lcy9FLUtMQVNTRS9ULU1PREVMTD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU2In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI0NjQzODE4ODQuMTc0NzEzNDk4NyJ9LCJhbm9uSWQiOiIyMDEwZmQ0ODc2ZjA3ZTFkIn0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiOTkzMTA1MzkyMDE0NjE4OCJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x561de87287fa <unknown>
#1 0x561de81cce90 <unknown>
#2 0x561de81b4156 <unknown>
#3 0x561de81b2a6a <unknown>
#4 0x561de81b31cf <unknown>
#5 0x561de81b3124 <unknown>
#6 0x561de81d111f <unknown>
#7 0x561de82763ca <unknown>
#8 0x561de8244242 <unknown>
#9 0x561de826a135 <unknown>
#10 0x561de8244013 <unknown>
#11 0x561de8210b3b <unknown>
#12 0x561de82117a1 <unknown>
#13 0x561de86edb9b <unknown>
#14 0x561de86f1a8a <unknown>
#15 0x561de86d5912 <unknown>
#16 0x561de86f2604 <unknown>
#17 0x561de86ba74f <unknown>
#18 0x561de8716678 <unknown>
#19 0x561de8716856 <unknown>
#20 0x561de8727666 <unknown>
#21 0x7fa9ec29caa4 <unknown>
#22 0x7fa9ec329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_spain_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNDY0MzgxODg0LjE3NDcxMzQ5ODcifSwiYW5vbklkIjoiMjAxMGZkNDg3NmYwN2UxZCJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5lcy9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvRVMvZXMvRS1LTEFTU0UvVC1NT0RFTEw%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1NiIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijc5ODUzOTc4NTM2Mjg4NjMiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x561de87287fa <unknown>
#1 0x561de81cce90 <unknown>
#2 0x561de81b4156 <unknown>
#3 0x561de81b2a6a <unknown>
#4 0x561de81b31cf <unknown>
#5 0x561de81b3124 <unknown>
#6 0x561de81d111f <unknown>
#7 0x561de82763ca <unknown>
#8 0x561de8244242 <unknown>
#9 0x561de826a135 <unknown>
#10 0x561de8244013 <unknown>
#11 0x561de8210b3b <unknown>
#12 0x561de82117a1 <unknown>
#13 0x561de86edb9b <unknown>
#14 0x561de86f1a8a <unknown>
#15 0x561de86d5912 <unknown>
#16 0x561de86f2604 <unknown>
#17 0x561de86ba74f <unknown>
#18 0x561de8716678 <unknown>
#19 0x561de8716856 <unknown>
#20 0x561de8727666 <unknown>
#21 0x7fa9ec29caa4 <unknown>
#22 0x7fa9ec329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: