ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5606c2ef57fa <unknown>
#1 0x5606c2999e90 <unknown>
#2 0x5606c29eb870 <unknown>
#3 0x5606c29eba91 <unknown>
#4 0x5606c29df446 <unknown>
#5 0x5606c2a1126d <unknown>
#6 0x5606c29df2fa <unknown>
#7 0x5606c2a1140e <unknown>
#8 0x5606c2a37135 <unknown>
#9 0x5606c2a11013 <unknown>
#10 0x5606c29ddb3b <unknown>
#11 0x5606c29de7a1 <unknown>
#12 0x5606c2ebab9b <unknown>
#13 0x5606c2ebea8a <unknown>
#14 0x5606c2ea2912 <unknown>
#15 0x5606c2ebf604 <unknown>
#16 0x5606c2e8774f <unknown>
#17 0x5606c2ee3678 <unknown>
#18 0x5606c2ee3856 <unknown>
#19 0x5606c2ef4666 <unknown>
#20 0x7f7db1a9caa4 <unknown>
#21 0x7f7db1b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_hungary_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNDkyMTQ3NzEzLjE3NDcxMzE0ODMifSwiYW5vbklkIjoiYjY2ODMzNjdiM2ZiZTRlNyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5odS9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvSFUvaHUvRS1LTEFTU0UvVC1NT0RFTEw%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MCIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijk2MjQzNzc2NTk1MTk1OCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5606c2ef57fa <unknown>
#1 0x5606c2999e90 <unknown>
#2 0x5606c2981156 <unknown>
#3 0x5606c297fa6a <unknown>
#4 0x5606c29801cf <unknown>
#5 0x5606c2980124 <unknown>
#6 0x5606c299e11f <unknown>
#7 0x5606c2a433ca <unknown>
#8 0x5606c2a11242 <unknown>
#9 0x5606c2a37135 <unknown>
#10 0x5606c2a11013 <unknown>
#11 0x5606c29ddb3b <unknown>
#12 0x5606c29de7a1 <unknown>
#13 0x5606c2ebab9b <unknown>
#14 0x5606c2ebea8a <unknown>
#15 0x5606c2ea2912 <unknown>
#16 0x5606c2ebf604 <unknown>
#17 0x5606c2e8774f <unknown>
#18 0x5606c2ee3678 <unknown>
#19 0x5606c2ee3856 <unknown>
#20 0x5606c2ef4666 <unknown>
#21 0x7f7db1a9caa4 <unknown>
#22 0x7f7db1b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_hungary_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiaHVfSFUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmh1L3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9IVS9odS9FLUtMQVNTRS9ULU1PREVMTD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYwIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI0OTIxNDc3MTMuMTc0NzEzMTQ4MyJ9LCJhbm9uSWQiOiJiNjY4MzM2N2IzZmJlNGU3In0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNzc1MzA3Mzg4NDQyMTc5MSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5606c2ef57fa <unknown>
#1 0x5606c2999e90 <unknown>
#2 0x5606c2981156 <unknown>
#3 0x5606c297fa6a <unknown>
#4 0x5606c29801cf <unknown>
#5 0x5606c2980124 <unknown>
#6 0x5606c299e11f <unknown>
#7 0x5606c2a433ca <unknown>
#8 0x5606c2a11242 <unknown>
#9 0x5606c2a37135 <unknown>
#10 0x5606c2a11013 <unknown>
#11 0x5606c29ddb3b <unknown>
#12 0x5606c29de7a1 <unknown>
#13 0x5606c2ebab9b <unknown>
#14 0x5606c2ebea8a <unknown>
#15 0x5606c2ea2912 <unknown>
#16 0x5606c2ebf604 <unknown>
#17 0x5606c2e8774f <unknown>
#18 0x5606c2ee3678 <unknown>
#19 0x5606c2ee3856 <unknown>
#20 0x5606c2ef4666 <unknown>
#21 0x7f7db1a9caa4 <unknown>
#22 0x7f7db1b29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: