ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x564fbaf367fa <unknown>
#1 0x564fba9dae90 <unknown>
#2 0x564fbaa2c870 <unknown>
#3 0x564fbaa2ca91 <unknown>
#4 0x564fbaa20446 <unknown>
#5 0x564fbaa5226d <unknown>
#6 0x564fbaa202fa <unknown>
#7 0x564fbaa5240e <unknown>
#8 0x564fbaa78135 <unknown>
#9 0x564fbaa52013 <unknown>
#10 0x564fbaa1eb3b <unknown>
#11 0x564fbaa1f7a1 <unknown>
#12 0x564fbaefbb9b <unknown>
#13 0x564fbaeffa8a <unknown>
#14 0x564fbaee3912 <unknown>
#15 0x564fbaf00604 <unknown>
#16 0x564fbaec874f <unknown>
#17 0x564fbaf24678 <unknown>
#18 0x564fbaf24856 <unknown>
#19 0x564fbaf35666 <unknown>
#20 0x7f2e3969caa4 <unknown>
#21 0x7f2e39729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZnJfTFUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmx1L2ZyL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9MVS9mci9HTEItS0xBU1NFL09GRlJPQURFUj9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU1In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI3MzE1Mjg0NjIuMTc0NzEzMzcwNCJ9LCJhbm9uSWQiOiI3M2NhNWVlMTM0OGRkYzU2In0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMjY0ODA3Mzk5ODY4Mzg2In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x564fbaf367fa <unknown>
#1 0x564fba9dae90 <unknown>
#2 0x564fba9c2156 <unknown>
#3 0x564fba9c0a6a <unknown>
#4 0x564fba9c11cf <unknown>
#5 0x564fba9c1124 <unknown>
#6 0x564fba9df11f <unknown>
#7 0x564fbaa843ca <unknown>
#8 0x564fbaa52242 <unknown>
#9 0x564fbaa78135 <unknown>
#10 0x564fbaa52013 <unknown>
#11 0x564fbaa1eb3b <unknown>
#12 0x564fbaa1f7a1 <unknown>
#13 0x564fbaefbb9b <unknown>
#14 0x564fbaeffa8a <unknown>
#15 0x564fbaee3912 <unknown>
#16 0x564fbaf00604 <unknown>
#17 0x564fbaec874f <unknown>
#18 0x564fbaf24678 <unknown>
#19 0x564fbaf24856 <unknown>
#20 0x564fbaf35666 <unknown>
#21 0x7f2e3969caa4 <unknown>
#22 0x7f2e39729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNzMxNTI4NDYyLjE3NDcxMzM3MDQifSwiYW5vbklkIjoiNzNjYTVlZTEzNDhkZGM1NiJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5sdS9mci9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvTFUvZnIvR0xCLUtMQVNTRS9PRkZST0FERVI%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1NSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjR9LCJfdG9vbHNFdmVudExpbmtJZCI6IjI5MzA2MTY0NTc0ODAwNDc1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x564fbaf367fa <unknown>
#1 0x564fba9dae90 <unknown>
#2 0x564fba9c2156 <unknown>
#3 0x564fba9c0a6a <unknown>
#4 0x564fba9c11cf <unknown>
#5 0x564fba9c1124 <unknown>
#6 0x564fba9df11f <unknown>
#7 0x564fbaa843ca <unknown>
#8 0x564fbaa52242 <unknown>
#9 0x564fbaa78135 <unknown>
#10 0x564fbaa52013 <unknown>
#11 0x564fbaa1eb3b <unknown>
#12 0x564fbaa1f7a1 <unknown>
#13 0x564fbaefbb9b <unknown>
#14 0x564fbaeffa8a <unknown>
#15 0x564fbaee3912 <unknown>
#16 0x564fbaf00604 <unknown>
#17 0x564fbaec874f <unknown>
#18 0x564fbaf24678 <unknown>
#19 0x564fbaf24856 <unknown>
#20 0x564fbaf35666 <unknown>
#21 0x7f2e3969caa4 <unknown>
#22 0x7f2e39729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: