ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x56291421c7fa <unknown>
#1 0x562913cc0e90 <unknown>
#2 0x562913d12870 <unknown>
#3 0x562913d12a91 <unknown>
#4 0x562913d06446 <unknown>
#5 0x562913d3826d <unknown>
#6 0x562913d062fa <unknown>
#7 0x562913d3840e <unknown>
#8 0x562913d5e135 <unknown>
#9 0x562913d38013 <unknown>
#10 0x562913d04b3b <unknown>
#11 0x562913d057a1 <unknown>
#12 0x5629141e1b9b <unknown>
#13 0x5629141e5a8a <unknown>
#14 0x5629141c9912 <unknown>
#15 0x5629141e6604 <unknown>
#16 0x5629141ae74f <unknown>
#17 0x56291420a678 <unknown>
#18 0x56291420a856 <unknown>
#19 0x56291421b666 <unknown>
#20 0x7f69f5c9caa4 <unknown>
#21 0x7f69f5d29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_romania_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoicm9fUk8iLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnJvL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9STy9yby9HTEItS0xBU1NFL09GRlJPQURFUj9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjY3In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxMTYyNTEyMjc0LjE3NDcxMzY0NjcifSwiYW5vbklkIjoiMzI1ODI0YmRjZjY2NjVhYyJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijc4OTUzMTMzNTI4MjMzIn0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x56291421c7fa <unknown>
#1 0x562913cc0e90 <unknown>
#2 0x562913ca8156 <unknown>
#3 0x562913ca6a6a <unknown>
#4 0x562913ca71cf <unknown>
#5 0x562913ca7124 <unknown>
#6 0x562913cc511f <unknown>
#7 0x562913d6a3ca <unknown>
#8 0x562913d38242 <unknown>
#9 0x562913d5e135 <unknown>
#10 0x562913d38013 <unknown>
#11 0x562913d04b3b <unknown>
#12 0x562913d057a1 <unknown>
#13 0x5629141e1b9b <unknown>
#14 0x5629141e5a8a <unknown>
#15 0x5629141c9912 <unknown>
#16 0x5629141e6604 <unknown>
#17 0x5629141ae74f <unknown>
#18 0x56291420a678 <unknown>
#19 0x56291420a856 <unknown>
#20 0x56291421b666 <unknown>
#21 0x7f69f5c9caa4 <unknown>
#22 0x7f69f5d29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_romania_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTE2MjUxMjI3NC4xNzQ3MTM2NDY3In0sImFub25JZCI6IjMyNTgyNGJkY2Y2NjY1YWMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnoucm8vcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL1JPL3JvL0dMQi1LTEFTU0UvT0ZGUk9BREVSP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjciLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIzNTE5NTIzNjI2NjUyMzE4IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x56291421c7fa <unknown>
#1 0x562913cc0e90 <unknown>
#2 0x562913ca8156 <unknown>
#3 0x562913ca6a6a <unknown>
#4 0x562913ca71cf <unknown>
#5 0x562913ca7124 <unknown>
#6 0x562913cc511f <unknown>
#7 0x562913d6a3ca <unknown>
#8 0x562913d38242 <unknown>
#9 0x562913d5e135 <unknown>
#10 0x562913d38013 <unknown>
#11 0x562913d04b3b <unknown>
#12 0x562913d057a1 <unknown>
#13 0x5629141e1b9b <unknown>
#14 0x5629141e5a8a <unknown>
#15 0x5629141c9912 <unknown>
#16 0x5629141e6604 <unknown>
#17 0x5629141ae74f <unknown>
#18 0x56291420a678 <unknown>
#19 0x56291420a856 <unknown>
#20 0x56291421b666 <unknown>
#21 0x7f69f5c9caa4 <unknown>
#22 0x7f69f5d29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: