ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x56304e4b57fa <unknown>
#1 0x56304df59e90 <unknown>
#2 0x56304dfab870 <unknown>
#3 0x56304dfaba91 <unknown>
#4 0x56304df9f446 <unknown>
#5 0x56304dfd126d <unknown>
#6 0x56304df9f2fa <unknown>
#7 0x56304dfd140e <unknown>
#8 0x56304dff7135 <unknown>
#9 0x56304dfd1013 <unknown>
#10 0x56304df9db3b <unknown>
#11 0x56304df9e7a1 <unknown>
#12 0x56304e47ab9b <unknown>
#13 0x56304e47ea8a <unknown>
#14 0x56304e462912 <unknown>
#15 0x56304e47f604 <unknown>
#16 0x56304e44774f <unknown>
#17 0x56304e4a3678 <unknown>
#18 0x56304e4a3856 <unknown>
#19 0x56304e4b4666 <unknown>
#20 0x7f365889caa4 <unknown>
#21 0x7f3658929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZGVfTFUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmx1L2RlL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9MVS9kZS9DTEEvU0hPT1RJTkclMjBCUkFLRT9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU1In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI2OTYxNTQ4MDguMTc0NzEzMzAwNiJ9LCJhbm9uSWQiOiIyNmRjMjZmMzU4NWQwYjFkIn0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiODgyMDY3NDMyNTM4NTY2In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x56304e4b57fa <unknown>
#1 0x56304df59e90 <unknown>
#2 0x56304df41156 <unknown>
#3 0x56304df3fa6a <unknown>
#4 0x56304df401cf <unknown>
#5 0x56304df40124 <unknown>
#6 0x56304df5e11f <unknown>
#7 0x56304e0033ca <unknown>
#8 0x56304dfd1242 <unknown>
#9 0x56304dff7135 <unknown>
#10 0x56304dfd1013 <unknown>
#11 0x56304df9db3b <unknown>
#12 0x56304df9e7a1 <unknown>
#13 0x56304e47ab9b <unknown>
#14 0x56304e47ea8a <unknown>
#15 0x56304e462912 <unknown>
#16 0x56304e47f604 <unknown>
#17 0x56304e44774f <unknown>
#18 0x56304e4a3678 <unknown>
#19 0x56304e4a3856 <unknown>
#20 0x56304e4b4666 <unknown>
#21 0x7f365889caa4 <unknown>
#22 0x7f3658929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjk2MTU0ODA4LjE3NDcxMzMwMDYifSwiYW5vbklkIjoiMjZkYzI2ZjM1ODVkMGIxZCJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5sdS9kZS9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvTFUvZGUvQ0xBL1NIT09USU5HJTIwQlJBS0U%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1NSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjZ9LCJfdG9vbHNFdmVudExpbmtJZCI6IjgwMDczMTc5OTg2NDUyMTEiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x56304e4b57fa <unknown>
#1 0x56304df59e90 <unknown>
#2 0x56304df41156 <unknown>
#3 0x56304df3fa6a <unknown>
#4 0x56304df401cf <unknown>
#5 0x56304df40124 <unknown>
#6 0x56304df5e11f <unknown>
#7 0x56304e0033ca <unknown>
#8 0x56304dfd1242 <unknown>
#9 0x56304dff7135 <unknown>
#10 0x56304dfd1013 <unknown>
#11 0x56304df9db3b <unknown>
#12 0x56304df9e7a1 <unknown>
#13 0x56304e47ab9b <unknown>
#14 0x56304e47ea8a <unknown>
#15 0x56304e462912 <unknown>
#16 0x56304e47f604 <unknown>
#17 0x56304e44774f <unknown>
#18 0x56304e4a3678 <unknown>
#19 0x56304e4a3856 <unknown>
#20 0x56304e4b4666 <unknown>
#21 0x7f365889caa4 <unknown>
#22 0x7f3658929c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: