ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x564b9f48b7fa <unknown>
#1 0x564b9ef2fe90 <unknown>
#2 0x564b9ef81870 <unknown>
#3 0x564b9ef81a91 <unknown>
#4 0x564b9ef75446 <unknown>
#5 0x564b9efa726d <unknown>
#6 0x564b9ef752fa <unknown>
#7 0x564b9efa740e <unknown>
#8 0x564b9efcd135 <unknown>
#9 0x564b9efa7013 <unknown>
#10 0x564b9ef73b3b <unknown>
#11 0x564b9ef747a1 <unknown>
#12 0x564b9f450b9b <unknown>
#13 0x564b9f454a8a <unknown>
#14 0x564b9f438912 <unknown>
#15 0x564b9f455604 <unknown>
#16 0x564b9f41d74f <unknown>
#17 0x564b9f479678 <unknown>
#18 0x564b9f479856 <unknown>
#19 0x564b9f48a666 <unknown>
#20 0x7ff513e9caa4 <unknown>
#21 0x7ff513f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZGVfTFUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmx1L2RlL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9MVS9kZS9HTEMtS0xBU1NFL0NPVVBFP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNTUifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjExODIyNTMwNzMuMTc0NzEzMjIzMiJ9LCJhbm9uSWQiOiI1ZmU1MjFiMTFmNzlmNjE3In0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNjAxNDc3MjYxMDk5Mjg0MiJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x564b9f48b7fa <unknown>
#1 0x564b9ef2fe90 <unknown>
#2 0x564b9ef17156 <unknown>
#3 0x564b9ef15a6a <unknown>
#4 0x564b9ef161cf <unknown>
#5 0x564b9ef16124 <unknown>
#6 0x564b9ef3411f <unknown>
#7 0x564b9efd93ca <unknown>
#8 0x564b9efa7242 <unknown>
#9 0x564b9efcd135 <unknown>
#10 0x564b9efa7013 <unknown>
#11 0x564b9ef73b3b <unknown>
#12 0x564b9ef747a1 <unknown>
#13 0x564b9f450b9b <unknown>
#14 0x564b9f454a8a <unknown>
#15 0x564b9f438912 <unknown>
#16 0x564b9f455604 <unknown>
#17 0x564b9f41d74f <unknown>
#18 0x564b9f479678 <unknown>
#19 0x564b9f479856 <unknown>
#20 0x564b9f48a666 <unknown>
#21 0x7ff513e9caa4 <unknown>
#22 0x7ff513f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTE4MjI1MzA3My4xNzQ3MTMyMjMyIn0sImFub25JZCI6IjVmZTUyMWIxMWY3OWY2MTcifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnoubHUvZGUvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0xVL2RlL0dMQy1LTEFTU0UvQ09VUEU%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1NSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijk3NTM0NzY5ODM4ODAyNDUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x564b9f48b7fa <unknown>
#1 0x564b9ef2fe90 <unknown>
#2 0x564b9ef17156 <unknown>
#3 0x564b9ef15a6a <unknown>
#4 0x564b9ef161cf <unknown>
#5 0x564b9ef16124 <unknown>
#6 0x564b9ef3411f <unknown>
#7 0x564b9efd93ca <unknown>
#8 0x564b9efa7242 <unknown>
#9 0x564b9efcd135 <unknown>
#10 0x564b9efa7013 <unknown>
#11 0x564b9ef73b3b <unknown>
#12 0x564b9ef747a1 <unknown>
#13 0x564b9f450b9b <unknown>
#14 0x564b9f454a8a <unknown>
#15 0x564b9f438912 <unknown>
#16 0x564b9f455604 <unknown>
#17 0x564b9f41d74f <unknown>
#18 0x564b9f479678 <unknown>
#19 0x564b9f479856 <unknown>
#20 0x564b9f48a666 <unknown>
#21 0x7ff513e9caa4 <unknown>
#22 0x7ff513f29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: