ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5647a3c327fa <unknown>
#1 0x5647a36d6e90 <unknown>
#2 0x5647a3728870 <unknown>
#3 0x5647a3728a91 <unknown>
#4 0x5647a371c446 <unknown>
#5 0x5647a374e26d <unknown>
#6 0x5647a371c2fa <unknown>
#7 0x5647a374e40e <unknown>
#8 0x5647a3774135 <unknown>
#9 0x5647a374e013 <unknown>
#10 0x5647a371ab3b <unknown>
#11 0x5647a371b7a1 <unknown>
#12 0x5647a3bf7b9b <unknown>
#13 0x5647a3bfba8a <unknown>
#14 0x5647a3bdf912 <unknown>
#15 0x5647a3bfc604 <unknown>
#16 0x5647a3bc474f <unknown>
#17 0x5647a3c20678 <unknown>
#18 0x5647a3c20856 <unknown>
#19 0x5647a3c31666 <unknown>
#20 0x7fdfb709caa4 <unknown>
#21 0x7fdfb7129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_hungary_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTQyNTkyNDI0NC4xNzQ3MTMyNzMxIn0sImFub25JZCI6IjJiODA1ZDU2M2JhM2ZiMWMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaHUvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0hVL2h1L1MtS0xBU1NFL0xJTU9VU0lORV9MQU5HP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjAiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxMDUwMjk4NzE0NTYzNjQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5647a3c327fa <unknown>
#1 0x5647a36d6e90 <unknown>
#2 0x5647a36be156 <unknown>
#3 0x5647a36bca6a <unknown>
#4 0x5647a36bd1cf <unknown>
#5 0x5647a36bd124 <unknown>
#6 0x5647a36db11f <unknown>
#7 0x5647a37803ca <unknown>
#8 0x5647a374e242 <unknown>
#9 0x5647a3774135 <unknown>
#10 0x5647a374e013 <unknown>
#11 0x5647a371ab3b <unknown>
#12 0x5647a371b7a1 <unknown>
#13 0x5647a3bf7b9b <unknown>
#14 0x5647a3bfba8a <unknown>
#15 0x5647a3bdf912 <unknown>
#16 0x5647a3bfc604 <unknown>
#17 0x5647a3bc474f <unknown>
#18 0x5647a3c20678 <unknown>
#19 0x5647a3c20856 <unknown>
#20 0x5647a3c31666 <unknown>
#21 0x7fdfb709caa4 <unknown>
#22 0x7fdfb7129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_hungary_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiaHVfSFUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmh1L3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9IVS9odS9TLUtMQVNTRS9MSU1PVVNJTkVfTEFORz9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYwIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxNDI1OTI0MjQ0LjE3NDcxMzI3MzEifSwiYW5vbklkIjoiMmI4MDVkNTYzYmEzZmIxYyJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjU3MjAwOTcxMzg0MzIyMTkifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5647a3c327fa <unknown>
#1 0x5647a36d6e90 <unknown>
#2 0x5647a36be156 <unknown>
#3 0x5647a36bca6a <unknown>
#4 0x5647a36bd1cf <unknown>
#5 0x5647a36bd124 <unknown>
#6 0x5647a36db11f <unknown>
#7 0x5647a37803ca <unknown>
#8 0x5647a374e242 <unknown>
#9 0x5647a3774135 <unknown>
#10 0x5647a374e013 <unknown>
#11 0x5647a371ab3b <unknown>
#12 0x5647a371b7a1 <unknown>
#13 0x5647a3bf7b9b <unknown>
#14 0x5647a3bfba8a <unknown>
#15 0x5647a3bdf912 <unknown>
#16 0x5647a3bfc604 <unknown>
#17 0x5647a3bc474f <unknown>
#18 0x5647a3c20678 <unknown>
#19 0x5647a3c20856 <unknown>
#20 0x5647a3c31666 <unknown>
#21 0x7fdfb709caa4 <unknown>
#22 0x7fdfb7129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: