ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5588d30057fa <unknown>
#1 0x5588d2aa9e90 <unknown>
#2 0x5588d2afb870 <unknown>
#3 0x5588d2afba91 <unknown>
#4 0x5588d2aef446 <unknown>
#5 0x5588d2b2126d <unknown>
#6 0x5588d2aef2fa <unknown>
#7 0x5588d2b2140e <unknown>
#8 0x5588d2b47135 <unknown>
#9 0x5588d2b21013 <unknown>
#10 0x5588d2aedb3b <unknown>
#11 0x5588d2aee7a1 <unknown>
#12 0x5588d2fcab9b <unknown>
#13 0x5588d2fcea8a <unknown>
#14 0x5588d2fb2912 <unknown>
#15 0x5588d2fcf604 <unknown>
#16 0x5588d2f9774f <unknown>
#17 0x5588d2ff3678 <unknown>
#18 0x5588d2ff3856 <unknown>
#19 0x5588d3004666 <unknown>
#20 0x7f953b89caa4 <unknown>
#21 0x7f953b929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_netherlands_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoibmxfTkwiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lm5sL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9OTC9ubC9FLUtMQVNTRS9ULU1PREVMTD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU3In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIyNTU1NzU2ODguMTc0NzEzNDc3NCJ9LCJhbm9uSWQiOiI0YmI4OGQ3NjNkNmUyODE3In0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNzQ1ODM0MDUzNDE4MTcyNyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5588d30057fa <unknown>
#1 0x5588d2aa9e90 <unknown>
#2 0x5588d2a91156 <unknown>
#3 0x5588d2a8fa6a <unknown>
#4 0x5588d2a901cf <unknown>
#5 0x5588d2a90124 <unknown>
#6 0x5588d2aae11f <unknown>
#7 0x5588d2b533ca <unknown>
#8 0x5588d2b21242 <unknown>
#9 0x5588d2b47135 <unknown>
#10 0x5588d2b21013 <unknown>
#11 0x5588d2aedb3b <unknown>
#12 0x5588d2aee7a1 <unknown>
#13 0x5588d2fcab9b <unknown>
#14 0x5588d2fcea8a <unknown>
#15 0x5588d2fb2912 <unknown>
#16 0x5588d2fcf604 <unknown>
#17 0x5588d2f9774f <unknown>
#18 0x5588d2ff3678 <unknown>
#19 0x5588d2ff3856 <unknown>
#20 0x5588d3004666 <unknown>
#21 0x7f953b89caa4 <unknown>
#22 0x7f953b929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_netherlands_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMjU1NTc1Njg4LjE3NDcxMzQ3NzQifSwiYW5vbklkIjoiNGJiODhkNzYzZDZlMjgxNyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5ubC9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvTkwvbmwvRS1LTEFTU0UvVC1NT0RFTEw%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1NyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjEyNzEzODQ2MDMyMzYzNTYzIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5588d30057fa <unknown>
#1 0x5588d2aa9e90 <unknown>
#2 0x5588d2a91156 <unknown>
#3 0x5588d2a8fa6a <unknown>
#4 0x5588d2a901cf <unknown>
#5 0x5588d2a90124 <unknown>
#6 0x5588d2aae11f <unknown>
#7 0x5588d2b533ca <unknown>
#8 0x5588d2b21242 <unknown>
#9 0x5588d2b47135 <unknown>
#10 0x5588d2b21013 <unknown>
#11 0x5588d2aedb3b <unknown>
#12 0x5588d2aee7a1 <unknown>
#13 0x5588d2fcab9b <unknown>
#14 0x5588d2fcea8a <unknown>
#15 0x5588d2fb2912 <unknown>
#16 0x5588d2fcf604 <unknown>
#17 0x5588d2f9774f <unknown>
#18 0x5588d2ff3678 <unknown>
#19 0x5588d2ff3856 <unknown>
#20 0x5588d3004666 <unknown>
#21 0x7f953b89caa4 <unknown>
#22 0x7f953b929c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: