ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5573afd5c7fa <unknown>
#1 0x5573af800e90 <unknown>
#2 0x5573af852870 <unknown>
#3 0x5573af852a91 <unknown>
#4 0x5573af846446 <unknown>
#5 0x5573af87826d <unknown>
#6 0x5573af8462fa <unknown>
#7 0x5573af87840e <unknown>
#8 0x5573af89e135 <unknown>
#9 0x5573af878013 <unknown>
#10 0x5573af844b3b <unknown>
#11 0x5573af8457a1 <unknown>
#12 0x5573afd21b9b <unknown>
#13 0x5573afd25a8a <unknown>
#14 0x5573afd09912 <unknown>
#15 0x5573afd26604 <unknown>
#16 0x5573afcee74f <unknown>
#17 0x5573afd4a678 <unknown>
#18 0x5573afd4a856 <unknown>
#19 0x5573afd5b666 <unknown>
#20 0x7f1fe989caa4 <unknown>
#21 0x7f1fe9929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjMwNTE1MTA4LjE3NDcxMzIxMDMifSwiYW5vbklkIjoiY2U4NjA4ZDEwNzhjYzk1YyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5sdS9kZS9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvTFUvZGUvUy1LTEFTU0UvTElNT1VTSU5FX0xBTkc%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1NSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjA5NzYzMDM0OTY3NzU3MDEyIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5573afd5c7fa <unknown>
#1 0x5573af800e90 <unknown>
#2 0x5573af7e8156 <unknown>
#3 0x5573af7e6a6a <unknown>
#4 0x5573af7e71cf <unknown>
#5 0x5573af7e7124 <unknown>
#6 0x5573af80511f <unknown>
#7 0x5573af8aa3ca <unknown>
#8 0x5573af878242 <unknown>
#9 0x5573af89e135 <unknown>
#10 0x5573af878013 <unknown>
#11 0x5573af844b3b <unknown>
#12 0x5573af8457a1 <unknown>
#13 0x5573afd21b9b <unknown>
#14 0x5573afd25a8a <unknown>
#15 0x5573afd09912 <unknown>
#16 0x5573afd26604 <unknown>
#17 0x5573afcee74f <unknown>
#18 0x5573afd4a678 <unknown>
#19 0x5573afd4a856 <unknown>
#20 0x5573afd5b666 <unknown>
#21 0x7f1fe989caa4 <unknown>
#22 0x7f1fe9929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZGVfTFUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmx1L2RlL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9MVS9kZS9TLUtMQVNTRS9MSU1PVVNJTkVfTEFORz9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU1In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI2MzA1MTUxMDguMTc0NzEzMjEwMyJ9LCJhbm9uSWQiOiJjZTg2MDhkMTA3OGNjOTVjIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE1Mjc5NzI4NDcxMDM1OTAzIn0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5573afd5c7fa <unknown>
#1 0x5573af800e90 <unknown>
#2 0x5573af7e8156 <unknown>
#3 0x5573af7e6a6a <unknown>
#4 0x5573af7e71cf <unknown>
#5 0x5573af7e7124 <unknown>
#6 0x5573af80511f <unknown>
#7 0x5573af8aa3ca <unknown>
#8 0x5573af878242 <unknown>
#9 0x5573af89e135 <unknown>
#10 0x5573af878013 <unknown>
#11 0x5573af844b3b <unknown>
#12 0x5573af8457a1 <unknown>
#13 0x5573afd21b9b <unknown>
#14 0x5573afd25a8a <unknown>
#15 0x5573afd09912 <unknown>
#16 0x5573afd26604 <unknown>
#17 0x5573afcee74f <unknown>
#18 0x5573afd4a678 <unknown>
#19 0x5573afd4a856 <unknown>
#20 0x5573afd5b666 <unknown>
#21 0x7f1fe989caa4 <unknown>
#22 0x7f1fe9929c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message:
ERROR    root:QAAppAllure.py:165 ❌ Failed to accept cookies.
ERROR    root:QAAppAllure.py:165 ❌ Failed to accept cookies.