ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=135.0.7049.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x56396085e75a <unknown>
#1 0x5639603114b0 <unknown>
#2 0x5639603629b3 <unknown>
#3 0x563960362bd1 <unknown>
#4 0x5639603564b6 <unknown>
#5 0x5639603885bd <unknown>
#6 0x56396035636a <unknown>
#7 0x56396038875e <unknown>
#8 0x5639603ae5e0 <unknown>
#9 0x563960388363 <unknown>
#10 0x563960354d63 <unknown>
#11 0x5639603559c1 <unknown>
#12 0x563960823a6b <unknown>
#13 0x563960827951 <unknown>
#14 0x56396080bb62 <unknown>
#15 0x5639608284c4 <unknown>
#16 0x5639607f013f <unknown>
#17 0x56396084c6f8 <unknown>
#18 0x56396084c8d6 <unknown>
#19 0x56396085d5a6 <unknown>
#20 0x7fb33cc9caa4 <unknown>
#21 0x7fb33cd29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_hungary_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiaHVfSFUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmh1L3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9IVS9odS9FUUUtS0xBU1NFL0xJTU9VU0lORV9MQU5HIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1OSJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTEzMzM2NzI5LjE3NDYzMTMzOTQifSwiYW5vbklkIjoiODk2NDY1Yzk1Y2Q3NzQyYiJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjIyNzgwMzg5MDM3Mzc2OTAyIn0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x56396085e75a <unknown>
#1 0x5639603114b0 <unknown>
#2 0x5639602f7d86 <unknown>
#3 0x5639602f669a <unknown>
#4 0x5639602f6dff <unknown>
#5 0x5639602f6d54 <unknown>
#6 0x56396031569f <unknown>
#7 0x5639603ba92a <unknown>
#8 0x563960388592 <unknown>
#9 0x5639603ae5e0 <unknown>
#10 0x563960388363 <unknown>
#11 0x563960354d63 <unknown>
#12 0x5639603559c1 <unknown>
#13 0x563960823a6b <unknown>
#14 0x563960827951 <unknown>
#15 0x56396080bb62 <unknown>
#16 0x5639608284c4 <unknown>
#17 0x5639607f013f <unknown>
#18 0x56396084c6f8 <unknown>
#19 0x56396084c8d6 <unknown>
#20 0x56396085d5a6 <unknown>
#21 0x7fb33cc9caa4 <unknown>
#22 0x7fb33cd29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_hungary_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTEzMzM2NzI5LjE3NDYzMTMzOTQifSwiYW5vbklkIjoiODk2NDY1Yzk1Y2Q3NzQyYiJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5odS9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvSFUvaHUvRVFFLUtMQVNTRS9MSU1PVVNJTkVfTEFORyIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNTkiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI1NDY1Njg1NjE0NDIwNTI2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x56396085e75a <unknown>
#1 0x5639603114b0 <unknown>
#2 0x5639602f7d86 <unknown>
#3 0x5639602f669a <unknown>
#4 0x5639602f6dff <unknown>
#5 0x5639602f6d54 <unknown>
#6 0x56396031569f <unknown>
#7 0x5639603ba92a <unknown>
#8 0x563960388592 <unknown>
#9 0x5639603ae5e0 <unknown>
#10 0x563960388363 <unknown>
#11 0x563960354d63 <unknown>
#12 0x5639603559c1 <unknown>
#13 0x563960823a6b <unknown>
#14 0x563960827951 <unknown>
#15 0x56396080bb62 <unknown>
#16 0x5639608284c4 <unknown>
#17 0x5639607f013f <unknown>
#18 0x56396084c6f8 <unknown>
#19 0x56396084c8d6 <unknown>
#20 0x56396085d5a6 <unknown>
#21 0x7fb33cc9caa4 <unknown>
#22 0x7fb33cd29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:127 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:QAAppAllure.py:172 ❌ Test 'Last Configuration Completed' failed.