ERROR    root:test_LastConfigCompleted.py:97 ❌ Error in configurator: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul > li:nth-child(3) > ccwb-text > a"}
  (Session info: chrome=135.0.7049.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x56126353075a <unknown>
#1 0x561262fe34b0 <unknown>
#2 0x5612630349b3 <unknown>
#3 0x561263034bd1 <unknown>
#4 0x5612630284b6 <unknown>
#5 0x56126305a5bd <unknown>
#6 0x56126302836a <unknown>
#7 0x56126305a75e <unknown>
#8 0x5612630805e0 <unknown>
#9 0x56126305a363 <unknown>
#10 0x561263026d63 <unknown>
#11 0x5612630279c1 <unknown>
#12 0x5612634f5a6b <unknown>
#13 0x5612634f9951 <unknown>
#14 0x5612634ddb62 <unknown>
#15 0x5612634fa4c4 <unknown>
#16 0x5612634c213f <unknown>
#17 0x56126351e6f8 <unknown>
#18 0x56126351e8d6 <unknown>
#19 0x56126352f5a6 <unknown>
#20 0x7f24c509caa4 <unknown>
#21 0x7f24c5129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:87 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Perso/QA-Perso/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:QAAppAllure.py:172 ❌ Test 'Last Configuration Completed' failed.
ERROR    root:test_LastConfigCompleted.py:97 ❌ Error in configurator: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul > li:nth-child(3) > ccwb-text > a"}
  (Session info: chrome=135.0.7049.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55560b8d375a <unknown>
#1 0x55560b3864b0 <unknown>
#2 0x55560b3d79b3 <unknown>
#3 0x55560b3d7bd1 <unknown>
#4 0x55560b3cb4b6 <unknown>
#5 0x55560b3fd5bd <unknown>
#6 0x55560b3cb36a <unknown>
#7 0x55560b3fd75e <unknown>
#8 0x55560b4235e0 <unknown>
#9 0x55560b3fd363 <unknown>
#10 0x55560b3c9d63 <unknown>
#11 0x55560b3ca9c1 <unknown>
#12 0x55560b898a6b <unknown>
#13 0x55560b89c951 <unknown>
#14 0x55560b880b62 <unknown>
#15 0x55560b89d4c4 <unknown>
#16 0x55560b86513f <unknown>
#17 0x55560b8c16f8 <unknown>
#18 0x55560b8c18d6 <unknown>
#19 0x55560b8d25a6 <unknown>
#20 0x7f694fc9caa4 <unknown>
#21 0x7f694fd29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:87 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Perso/QA-Perso/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:QAAppAllure.py:172 ❌ Test 'Last Configuration Completed' failed.
ERROR    root:test_LastConfigCompleted.py:97 ❌ Error in configurator: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul > li:nth-child(3) > ccwb-text > a"}
  (Session info: chrome=135.0.7049.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x556025dc675a <unknown>
#1 0x5560258794b0 <unknown>
#2 0x5560258ca9b3 <unknown>
#3 0x5560258cabd1 <unknown>
#4 0x5560258be4b6 <unknown>
#5 0x5560258f05bd <unknown>
#6 0x5560258be36a <unknown>
#7 0x5560258f075e <unknown>
#8 0x5560259165e0 <unknown>
#9 0x5560258f0363 <unknown>
#10 0x5560258bcd63 <unknown>
#11 0x5560258bd9c1 <unknown>
#12 0x556025d8ba6b <unknown>
#13 0x556025d8f951 <unknown>
#14 0x556025d73b62 <unknown>
#15 0x556025d904c4 <unknown>
#16 0x556025d5813f <unknown>
#17 0x556025db46f8 <unknown>
#18 0x556025db48d6 <unknown>
#19 0x556025dc55a6 <unknown>
#20 0x7f6760a9caa4 <unknown>
#21 0x7f6760b29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:87 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Perso/QA-Perso/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:QAAppAllure.py:172 ❌ Test 'Last Configuration Completed' failed.